### ISSUE TITLE
NodeJS SDK: Execute dagger sdk from within a container: spawn Unknown system error -8

### ISSUE THREAD

**Issue by marcindulak** [dagger/dagger#3857]
### What are you trying to do?

Execute nodejs sdk example from https://github.com/dagger/dagger/pull/3823 inside of a container that mounts `/var/run/docker.sock` (so called Docker Outside of Docker (DooD) setup).

To reproduce, use the following `Dockerfile`:
```
FROM node:18.12.1-alpine3.16

RUN apk update \
    && apk add shadow docker-cli \
    && rm -rf /var/cache/apk/*
RUN addgroup -S docker && adduser node docker

WORKDIR /app

CMD ["sleep", "infinity"]
```

and run:
```
docker rm -f dagger
docker build -t dagger:latest .
docker run -d --rm --name dagger -v /var/run/docker.sock:/var/run/docker.sock dagger:latest sleep infinity
docker exec -it dagger sh -c "groupmod -g \$(stat -c '%g' /var/run/docker.sock) docker"
docker exec -it dagger sh -c "docker run hello-world"
docker exec -it dagger sh -c "npm install ts-node"
docker exec -it dagger sh -c "npm pkg set type=module"
# Need tsconfig.json, otherwise getting "ReferenceError: exports is not defined in ES module scope"
# the https://github.com/dagger/dagger/pull/3823 doc may be incomplete/untested
docker exec -it dagger sh -c "echo '{\"compilerOptions\":{\"moduleResolution\":\"Node\",\"module\":\"ESNext\"}}' > tsconfig.json"
docker exec -it dagger sh -c "npm install @dagger.io/dagger@0.1.0-alpha.2"
docker exec -it dagger sh -c "echo 'import Client, { connect } from \"@dagger.io/dagger\"' > build.ts"
docker exec -it dagger sh -c "echo 'connect(async (client: Client) => {})' >> build.ts"
docker exec -it dagger sh -c "node --loader ts-node/esm ./build.ts"
```

Output:
```
(node:97) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Command failed with Unknown system error -8: /root/.cache/dagger/dagger-engine-session-666b958a2f716c0d --remote docker-image://ghcr.io/dagger/engine:v0.3.4@sha256:666b958a2f716c0d6b22d869c585d6fe07954133ec769bb3d1f310e931cb118f --workdir /app
spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:743:9)
    at execa (file:///app/node_modules/execa/index.js:84:26)
    at execaCommand (file:///app/node_modules/execa/index.js:229:9)
    at DockerImage.<anonymous> (file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:183:31)
    at Generator.next (<anonymous>)
    at file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:3:12)
    at DockerImage.runEngineSession (file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:175:16) {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn',
  originalMessage: 'spawn Unknown system error -8',
  shortMessage: 'Command failed with Unknown system error -8: /root/.cache/dagger/dagger-engine-session-666b958a2f716c0d --remote docker-image://ghcr.io/dagger/engine:v0.3.4@sha256:666b958a2f716c0d6b22d869c585d6fe07954133ec769bb3d1f310e931cb118f --workdir /app\n' +
    'spawn Unknown system error -8',
  command: '/root/.cache/dagger/dagger-engine-session-666b958a2f716c0d --remote docker-image://ghcr.io/dagger/engine:v0.3.4@sha256:666b958a2f716c0d6b22d869c585d6fe07954133ec769bb3d1f310e931cb118f --workdir /app',
  escapedCommand: '"/root/.cache/dagger/dagger-engine-session-666b958a2f716c0d" --remote "docker-image://ghcr.io/dagger/engine:v0.3.4@sha256:666b958a2f716c0d6b22d869c585d6fe07954133ec769bb3d1f310e931cb118f" --workdir "/app"',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  all: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

The host environment:
```
cat /etc/*release | grep PRETTY
PRETTY_NAME="Ubuntu 20.04.5 LTS"
```

```
docker version 
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:45 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:09:37 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Why is this important to you?

The dagger sdk documentation provides a [traditional path](https://docs.dagger.io/sdk/python/866944/install) with developer managing a given programming language environment on the machine.  When configuring developer machines it may be preferable that no software is installed, except for docker, graphical programs and possibly single binaries, and all commands to be executed inside of containers. Another use case of DooD is when executing CI pipelines from custom containers.

### How are you currently working around this?

Unknown

**Comment by marcindulak** [comment]
With https://www.npmjs.com/package/@dagger.io/dagger/v/0.1.0-alpha.3 I'm getting:

```
(node:97) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:149
            throw new Error(`failed to copy engine session binary: ${e}`);
                  ^
Error: failed to copy engine session binary: Error: Command failed with exit code 1: docker run --rm --entrypoint /bin/cat ghcr.io/dagger/engine:v0.3.4@sha256:666b958a2f716c0d6b22d869c585d6fe07954133ec769bb3d1f310e931cb118f /usr/bin/dagger-engine-session-linux-x64
cat: can't open '/usr/bin/dagger-engine-session-linux-x64': No such file or directory
    at DockerImage.pullEngineSessionBin (file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:149:19)
    at DockerImage.<anonymous> (file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:83:22)
    at Generator.next (<anonymous>)
    at file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:3:12)
    at DockerImage.Connect (file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:79:16)
    at file:///app/node_modules/@dagger.io/dagger/dist/connect.js:24:36
    at Generator.next (<anonymous>)
    at file:///app/node_modules/@dagger.io/dagger/dist/connect.js:7:71
```

**Comment by sipsma** [comment]
> With https://www.npmjs.com/package/@dagger.io/dagger/v/0.1.0-alpha.3 I'm getting:

Sorry @marcindulak you keep hitting issues as we hit them and fix them in parallel, that issue was fixed here and should be out in a new alpha soon https://github.com/dagger/dagger/pull/3858

**Comment by marcindulak** [comment]
My original example works now when installing the latest `docker exec -it dagger sh -c "npm install @dagger.io/dagger"`, however only after some adjustements to the nodejs sdk docs https://github.com/dagger/dagger/pull/3823. I'll open an additional issue.

I see that https://www.npmjs.com/package/@dagger.io/dagger/v/0.1.0-alpha.3 has been removed, `0.1.0-alpha.2` (a new upload?) is still present, and this step fails:

```
docker exec -it dagger sh -c "npm install @dagger.io/dagger@0.1.0-alpha.2"
...
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @dagger.io/dagger@0.1.0-alpha.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
Can you check whether there is something wrong with versioning of the package?

**Comment by marcindulak** [comment]
I was not able to reproduce the additional issue in https://github.com/dagger/dagger/pull/3823 I mentioned above: the problem was due to skipping of `npx create-react-app my-app --template typescript` so `tsconfig.json` was missing, as can be seen in my original example.

**Comment by marcindulak** [comment]
The new `docker exec -it dagger sh -c "npm install @dagger.io/dagger@0.1.0"` is installable, and it looks like the originally reported `spawn Unknown system error -8` issue is fixed.

**Comment by slumbering** [comment]
Closing this issue as fixed. @marcindulak Feel free to reopen it if needed. Thanks
